version: '3.8'

services:
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data  # Mounting persistent data for Mongo
    
    networks:
      - my_network
  # Rabbitmq Service
  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
     - RABBITMQ_DEFAULT_USER=user
     - RABBITMQ_DEFAULT_PASS=pass
     - VM_MEMORY_HIGH_WATERMARK=0.8
     - DISK_FREE_LIMIT=50MB
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 10s
      retries: 5
    networks:
      - my_network
    restart: unless-stopped
    
# Product Microservice
  frontend:
    build: ./client
    container_name: client
    env_file:
      - ./client/.env
    ports:
      - "3000:3000"
    networks:
      - my_network
    restart: unless-stopped

  # Gateway Service
  gateway:
    build: ./api-gateway
    container_name: gateway
    depends_on:
      - rabbitmq
    env_file:
      - ./api-gateway/.env
    ports:
      - "5000:5000"
    networks:
      - my_network
    restart: unless-stopped

  # Product Microservice
  product-service:
    build: ./product-service
    container_name: product-service
    
    env_file:
      - ./product-service/.env
    depends_on:
      - gateway
      - rabbitmq
    networks:
      - my_network
    restart: unless-stopped
    

  # Product Microservice
  user-service:
    build: ./user-service
    container_name: user-service
    env_file:
      - ./user-service/.env
    depends_on:
      - gateway
      - rabbitmq
    networks:
      - my_network
    restart: unless-stopped

networks:
  my_network:
    driver: bridge
volumes:
  mongo_data:
    driver: local